# -*- python -*-
Import('env')
Import('ast_lib')
Import('lexer_lib')

parser_lib = env.StaticLibrary(target='parser', source=['Parser.cpp', '../ast/Ast.cpp'])
Export('parser_lib')

tests = env.BoostTests(Glob("tests/*.cpp"), parser_lib, [ast_lib, lexer_lib])

Return('parser_lib')
