# -*- python -*-
Import('env')
Import('lexer_lib')

parser_lib = env.StaticLibrary(target='parser', source=Glob('*.cpp'))
Export('parser_lib')

tests = env.BoostTests(Glob("tests/*.cpp"), parser_lib, [lexer_lib])

Return('parser_lib')
