# -*- python -*-
Import('env')
lexer_lib = env.StaticLibrary('lexer', [Glob('*.cpp'), "../HexgridErrors.cpp"])
Export('lexer_lib')

tests = env.BoostTests(Glob("tests/*.cpp"), lexer_lib)

Return('lexer_lib')
