# -*- python -*-
Import('env')
lexer_lib = env.SConscript('lexer/SConscript')
parser_lib = env.SConscript('parser/SConscript')
interpreter_lib = env.SConscript('interpreter/SConscript')

# p = env.Program()
p = env.Program('hexgrider',
                ['main.cpp'],
                LIBS=[
                      lexer_lib, 
                      parser_lib,
                      interpreter_lib,
                  ])


Return('p')