# -*- python -*-
Import('env')

ast_lib = env.SConscript('ast/SConscript')
lexer_lib = env.SConscript('lexer/SConscript')
parser_lib = env.SConscript('parser/SConscript')

p = env.Program('tkom-calculator',
                ['main.cpp'],
                LIBS=[
                      ast_lib,
                      lexer_lib, 
                      parser_lib,
                  ])


Return('p')